export interface HappThemeConfig {
  backgroundGradientRotationAngle: number;
  backgroundGradientColorIntensity: number;
  backgroundColors: [string, string, string];
  serverRowBackgroundColor: string;
  selectedServerRowColor: string;
  subsHeaderColor: string;
  buttonColor: string;
  buttonTextColor: string;
  powerIconColor: string;
  serverRowTitleTextColor: string;
  serverRowSubTitleTextColor: string;
  topBarButtonsColor: string;
  supportIconColor: string;
  profileWebPageIconColor: string;
  subHeaderButtonColor: string;
  settingsControlsTintColor: string;
  subscriptionInfoBackgroundColor: string;
  subscriptionTrafficBackgroundColor: string;
  subscriptionInfoTextColor: string;
  disclosureHeaderTextColor: string;
  disclosureSubHeaderTextColor: string;
  serverRowChevronColor: string;
  additionalOptionsButtonColor: string;
  buttonTimerColor: string;
  elipseColors: [string, string, string];
  backgroundImageType: "light" | "dark" | "system";
  buttonImageType: "light" | "dark";
}

export interface PresetTheme {
  id: string;
  name: string;
  swatches: [string, string];
  config: HappThemeConfig;
}

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: "qone-black",
    name: "qOne Black",
    swatches: ["#000000", "#FFFFFF"],
    config: {
      backgroundGradientRotationAngle: 0,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#000000FF", "#080808FF", "#111111FF"],
      serverRowBackgroundColor: "#121212FF",
      selectedServerRowColor: "#222222FF",
      subsHeaderColor: "#161616FF",
      buttonColor: "#FFFFFFFF",
      buttonTextColor: "#000000FF",
      powerIconColor: "#404040FF",
      serverRowTitleTextColor: "#FFFFFFFF",
      serverRowSubTitleTextColor: "#8E8E93FF",
      topBarButtonsColor: "#FFFFFFFF",
      supportIconColor: "#FFFFFFFF",
      profileWebPageIconColor: "#FFFFFFFF",
      subHeaderButtonColor: "#FFFFFFFF",
      settingsControlsTintColor: "#FFFFFFFF",
      subscriptionInfoBackgroundColor: "#141414FF",
      subscriptionTrafficBackgroundColor: "#282828FF",
      subscriptionInfoTextColor: "#FFFFFFFF",
      disclosureHeaderTextColor: "#FFFFFFFF",
      disclosureSubHeaderTextColor: "#8E8E93FF",
      serverRowChevronColor: "#8E8E93FF",
      additionalOptionsButtonColor: "#FFFFFFFF",
      buttonTimerColor: "#FFFFFFFF",
      elipseColors: ["#2C2C2CFF", "#181818FF", "#383838FF"],
      backgroundImageType: "dark",
      buttonImageType: "dark"
    }
  },
  {
    id: "graphite",
    name: "Graphite",
    swatches: ["#17181C", "#E8E9EC"],
    config: {
      backgroundGradientRotationAngle: 45,
      backgroundGradientColorIntensity: 0.9,
      backgroundColors: ["#121316FF", "#17181CFF", "#22242AFF"],
      serverRowBackgroundColor: "#1C1E24FF",
      selectedServerRowColor: "#2E323CFF",
      subsHeaderColor: "#242730FF",
      buttonColor: "#E8E9ECFF",
      buttonTextColor: "#17181CFF",
      powerIconColor: "#454A56FF",
      serverRowTitleTextColor: "#F2F3F5FF",
      serverRowSubTitleTextColor: "#9AA0B0FF",
      topBarButtonsColor: "#D1D5DBFF",
      supportIconColor: "#D1D5DBFF",
      profileWebPageIconColor: "#D1D5DBFF",
      subHeaderButtonColor: "#D1D5DBFF",
      settingsControlsTintColor: "#E8E9ECFF",
      subscriptionInfoBackgroundColor: "#1E2027FF",
      subscriptionTrafficBackgroundColor: "#333742FF",
      subscriptionInfoTextColor: "#F2F3F5FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#9AA0B0FF",
      serverRowChevronColor: "#9AA0B0FF",
      additionalOptionsButtonColor: "#D1D5DBFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#3A3E4CFF", "#282B34FF", "#505668FF"],
      backgroundImageType: "dark",
      buttonImageType: "dark"
    }
  },
  {
    id: "sakura",
    name: "Sakura",
    swatches: ["#230C16", "#FF72A1"],
    config: {
      backgroundGradientRotationAngle: 55,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#14060CFF", "#230C16FF", "#3B1527FF"],
      serverRowBackgroundColor: "#2C111EFF",
      selectedServerRowColor: "#4D1F34FF",
      subsHeaderColor: "#391627FF",
      buttonColor: "#FF72A1FF",
      buttonTextColor: "#17040BFF",
      powerIconColor: "#612241FF",
      serverRowTitleTextColor: "#FFF0F5FF",
      serverRowSubTitleTextColor: "#ECAEC5FF",
      topBarButtonsColor: "#FF72A1FF",
      supportIconColor: "#FF72A1FF",
      profileWebPageIconColor: "#FF72A1FF",
      subHeaderButtonColor: "#FF72A1FF",
      settingsControlsTintColor: "#FF72A1FF",
      subscriptionInfoBackgroundColor: "#250E1AFF",
      subscriptionTrafficBackgroundColor: "#5C243EFF",
      subscriptionInfoTextColor: "#FFF0F5FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#ECAEC5FF",
      serverRowChevronColor: "#FF72A1FF",
      additionalOptionsButtonColor: "#FF72A1FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#FF72A1FF", "#C93769FF", "#FFA4C4FF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "titanium",
    name: "Titanium",
    swatches: ["#1F1F21", "#D1D5DB"],
    config: {
      backgroundGradientRotationAngle: 30,
      backgroundGradientColorIntensity: 0.85,
      backgroundColors: ["#131314FF", "#1F1F21FF", "#2B2B2EFF"],
      serverRowBackgroundColor: "#232326FF",
      selectedServerRowColor: "#39393DFF",
      subsHeaderColor: "#2A2A2DFF",
      buttonColor: "#D1D5DBFF",
      buttonTextColor: "#111827FF",
      powerIconColor: "#4B4D54FF",
      serverRowTitleTextColor: "#F9FAFBFF",
      serverRowSubTitleTextColor: "#9CA3AFFF",
      topBarButtonsColor: "#D1D5DBFF",
      supportIconColor: "#D1D5DBFF",
      profileWebPageIconColor: "#D1D5DBFF",
      subHeaderButtonColor: "#D1D5DBFF",
      settingsControlsTintColor: "#D1D5DBFF",
      subscriptionInfoBackgroundColor: "#1B1B1DFF",
      subscriptionTrafficBackgroundColor: "#37373CFF",
      subscriptionInfoTextColor: "#F9FAFBFF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#9CA3AFFF",
      serverRowChevronColor: "#9CA3AFFF",
      additionalOptionsButtonColor: "#D1D5DBFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#9CA3AFFF", "#6B7280FF", "#E5E7EBFF"],
      backgroundImageType: "dark",
      buttonImageType: "dark"
    }
  },
  {
    id: "cobalt",
    name: "Cobalt",
    swatches: ["#001D33", "#23B7FF"],
    config: {
      backgroundGradientRotationAngle: 55,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#00101CFF", "#001D33FF", "#00345BFF"],
      serverRowBackgroundColor: "#06253AFF",
      selectedServerRowColor: "#064D78FF",
      subsHeaderColor: "#063C61FF",
      buttonColor: "#23B7FFFF",
      buttonTextColor: "#00111DFF",
      powerIconColor: "#00375AFF",
      serverRowTitleTextColor: "#F0FAFFFF",
      serverRowSubTitleTextColor: "#9AC6DFFF",
      topBarButtonsColor: "#4CC5FFFF",
      supportIconColor: "#4CC5FFFF",
      profileWebPageIconColor: "#4CC5FFFF",
      subHeaderButtonColor: "#4CC5FFFF",
      settingsControlsTintColor: "#23B7FFFF",
      subscriptionInfoBackgroundColor: "#05273DFF",
      subscriptionTrafficBackgroundColor: "#07527DFF",
      subscriptionInfoTextColor: "#F0FAFFFF",
      disclosureHeaderTextColor: "#FFFFFFFF",
      disclosureSubHeaderTextColor: "#9AC6DFFF",
      serverRowChevronColor: "#4CC5FFFF",
      additionalOptionsButtonColor: "#4CC5FFFF",
      buttonTimerColor: "#FFFFFFFF",
      elipseColors: ["#23B7FFFF", "#0077FFFF", "#80E8FFFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "acid-lime",
    name: "Acid Lime",
    swatches: ["#101600", "#C8FF00"],
    config: {
      backgroundGradientRotationAngle: 45,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#090D00FF", "#101600FF", "#1D2800FF"],
      serverRowBackgroundColor: "#1A2202FF",
      selectedServerRowColor: "#2F3D05FF",
      subsHeaderColor: "#222D03FF",
      buttonColor: "#C8FF00FF",
      buttonTextColor: "#101600FF",
      powerIconColor: "#3E4E06FF",
      serverRowTitleTextColor: "#F8FFD9FF",
      serverRowSubTitleTextColor: "#C8DE76FF",
      topBarButtonsColor: "#C8FF00FF",
      supportIconColor: "#C8FF00FF",
      profileWebPageIconColor: "#C8FF00FF",
      subHeaderButtonColor: "#C8FF00FF",
      settingsControlsTintColor: "#C8FF00FF",
      subscriptionInfoBackgroundColor: "#161E02FF",
      subscriptionTrafficBackgroundColor: "#334204FF",
      subscriptionInfoTextColor: "#F8FFD9FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#C8DE76FF",
      serverRowChevronColor: "#C8FF00FF",
      additionalOptionsButtonColor: "#C8FF00FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#C8FF00FF", "#95BF00FF", "#E1FF66FF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "abyss",
    name: "Abyss",
    swatches: ["#071027", "#5A8DFF"],
    config: {
      backgroundGradientRotationAngle: 60,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#040817FF", "#071027FF", "#0E1E45FF"],
      serverRowBackgroundColor: "#0E1A3AFF",
      selectedServerRowColor: "#172C61FF",
      subsHeaderColor: "#122047FF",
      buttonColor: "#5A8DFFFF",
      buttonTextColor: "#050B1CFF",
      powerIconColor: "#1C336DFF",
      serverRowTitleTextColor: "#F0F4FFFF",
      serverRowSubTitleTextColor: "#A0B5E8FF",
      topBarButtonsColor: "#5A8DFFFF",
      supportIconColor: "#5A8DFFFF",
      profileWebPageIconColor: "#5A8DFFFF",
      subHeaderButtonColor: "#5A8DFFFF",
      settingsControlsTintColor: "#5A8DFFFF",
      subscriptionInfoBackgroundColor: "#0D1733FF",
      subscriptionTrafficBackgroundColor: "#1B3475FF",
      subscriptionInfoTextColor: "#F0F4FFFF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#A0B5E8FF",
      serverRowChevronColor: "#5A8DFFFF",
      additionalOptionsButtonColor: "#5A8DFFFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#5A8DFFFF", "#345EC4FF", "#8AB0FFFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "malachite",
    name: "Malachite",
    swatches: ["#06150C", "#35F06F"],
    config: {
      backgroundGradientRotationAngle: 60,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#030B06FF", "#06150CFF", "#0A2012FF"],
      serverRowBackgroundColor: "#0A1D11FF",
      selectedServerRowColor: "#113A21FF",
      subsHeaderColor: "#0D2C19FF",
      buttonColor: "#35F06FFF",
      buttonTextColor: "#021206FF",
      powerIconColor: "#0E4822FF",
      serverRowTitleTextColor: "#EDFDF3FF",
      serverRowSubTitleTextColor: "#86E0A6FF",
      topBarButtonsColor: "#35F06FFF",
      supportIconColor: "#35F06FFF",
      profileWebPageIconColor: "#35F06FFF",
      subHeaderButtonColor: "#35F06FFF",
      settingsControlsTintColor: "#35F06FFF",
      subscriptionInfoBackgroundColor: "#081F11FF",
      subscriptionTrafficBackgroundColor: "#124225FF",
      subscriptionInfoTextColor: "#EDFDF3FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#86E0A6FF",
      serverRowChevronColor: "#35F06FFF",
      additionalOptionsButtonColor: "#35F06FFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#35F06FFF", "#1AA04AFF", "#6BF59CFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "amethyst",
    name: "Amethyst",
    swatches: ["#150824", "#B847FF"],
    config: {
      backgroundGradientRotationAngle: 45,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#0D0417FF", "#150824FF", "#280F42FF"],
      serverRowBackgroundColor: "#200D34FF",
      selectedServerRowColor: "#3B1860FF",
      subsHeaderColor: "#2B1147FF",
      buttonColor: "#B847FFFF",
      buttonTextColor: "#120320FF",
      powerIconColor: "#4B1B7DFF",
      serverRowTitleTextColor: "#F9F2FFFF",
      serverRowSubTitleTextColor: "#D2A2F8FF",
      topBarButtonsColor: "#B847FFFF",
      supportIconColor: "#B847FFFF",
      profileWebPageIconColor: "#B847FFFF",
      subHeaderButtonColor: "#B847FFFF",
      settingsControlsTintColor: "#B847FFFF",
      subscriptionInfoBackgroundColor: "#1B0B2CFF",
      subscriptionTrafficBackgroundColor: "#441C6EFF",
      subscriptionInfoTextColor: "#F9F2FFFF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#D2A2F8FF",
      serverRowChevronColor: "#B847FFFF",
      additionalOptionsButtonColor: "#B847FFFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#B847FFFF", "#8018C7FF", "#DA8FFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "inferno",
    name: "Inferno",
    swatches: ["#220A0A", "#FF5449"],
    config: {
      backgroundGradientRotationAngle: 50,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#140505FF", "#220A0AFF", "#3B1212FF"],
      serverRowBackgroundColor: "#2C0F0FFF",
      selectedServerRowColor: "#4E1A1AFF",
      subsHeaderColor: "#3A1313FF",
      buttonColor: "#FF5449FF",
      buttonTextColor: "#1C0404FF",
      powerIconColor: "#661E1EFF",
      serverRowTitleTextColor: "#FFF2F2FF",
      serverRowSubTitleTextColor: "#ECA5A5FF",
      topBarButtonsColor: "#FF5449FF",
      supportIconColor: "#FF5449FF",
      profileWebPageIconColor: "#FF5449FF",
      subHeaderButtonColor: "#FF5449FF",
      settingsControlsTintColor: "#FF5449FF",
      subscriptionInfoBackgroundColor: "#260D0DFF",
      subscriptionTrafficBackgroundColor: "#5C1E1EFF",
      subscriptionInfoTextColor: "#FFF2F2FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#ECA5A5FF",
      serverRowChevronColor: "#FF5449FF",
      additionalOptionsButtonColor: "#FF5449FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#FF5449FF", "#C42525FF", "#FF8A8AFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "solar-gold",
    name: "Solar Gold",
    swatches: ["#1F1300", "#FFAA00"],
    config: {
      backgroundGradientRotationAngle: 45,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#120A00FF", "#1F1300FF", "#382300FF"],
      serverRowBackgroundColor: "#2E1B00FF",
      selectedServerRowColor: "#4E2F00FF",
      subsHeaderColor: "#3C2400FF",
      buttonColor: "#FFAA00FF",
      buttonTextColor: "#170D00FF",
      powerIconColor: "#633C00FF",
      serverRowTitleTextColor: "#FFFBF0FF",
      serverRowSubTitleTextColor: "#E8CA8CFF",
      topBarButtonsColor: "#FFAA00FF",
      supportIconColor: "#FFAA00FF",
      profileWebPageIconColor: "#FFAA00FF",
      subHeaderButtonColor: "#FFAA00FF",
      settingsControlsTintColor: "#FFAA00FF",
      subscriptionInfoBackgroundColor: "#261700FF",
      subscriptionTrafficBackgroundColor: "#5C3900FF",
      subscriptionInfoTextColor: "#FFFBF0FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#E8CA8CFF",
      serverRowChevronColor: "#FFAA00FF",
      additionalOptionsButtonColor: "#FFAA00FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#FFAA00FF", "#FB8500FF", "#FFD166FF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "glacier",
    name: "Glacier",
    swatches: ["#0A151D", "#6DD3E8"],
    config: {
      backgroundGradientRotationAngle: 45,
      backgroundGradientColorIntensity: 0.9,
      backgroundColors: ["#060E14FF", "#0A151DFF", "#152838FF"],
      serverRowBackgroundColor: "#12202EFF",
      selectedServerRowColor: "#1E364EFF",
      subsHeaderColor: "#182C3EFF",
      buttonColor: "#6DD3E8FF",
      buttonTextColor: "#08131AFF",
      powerIconColor: "#254B6EFF",
      serverRowTitleTextColor: "#F1F8FBFF",
      serverRowSubTitleTextColor: "#A6CCE0FF",
      topBarButtonsColor: "#6DD3E8FF",
      supportIconColor: "#6DD3E8FF",
      profileWebPageIconColor: "#6DD3E8FF",
      subHeaderButtonColor: "#6DD3E8FF",
      settingsControlsTintColor: "#6DD3E8FF",
      subscriptionInfoBackgroundColor: "#101D28FF",
      subscriptionTrafficBackgroundColor: "#23415EFF",
      subscriptionInfoTextColor: "#F1F8FBFF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#A6CCE0FF",
      serverRowChevronColor: "#6DD3E8FF",
      additionalOptionsButtonColor: "#6DD3E8FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#6DD3E8FF", "#3FA8C0FF", "#A2DEEDFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "crimson-noir",
    name: "Crimson Noir",
    swatches: ["#1C070E", "#E63956"],
    config: {
      backgroundGradientRotationAngle: 50,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#100307FF", "#1C070EFF", "#330E1AFF"],
      serverRowBackgroundColor: "#240A13FF",
      selectedServerRowColor: "#421323FF",
      subsHeaderColor: "#300D1AFF",
      buttonColor: "#E63956FF",
      buttonTextColor: "#120207FF",
      powerIconColor: "#5C1523FF",
      serverRowTitleTextColor: "#FFF0F3FF",
      serverRowSubTitleTextColor: "#ECA3B0FF",
      topBarButtonsColor: "#E63956FF",
      supportIconColor: "#E63956FF",
      profileWebPageIconColor: "#E63956FF",
      subHeaderButtonColor: "#E63956FF",
      settingsControlsTintColor: "#E63956FF",
      subscriptionInfoBackgroundColor: "#200911FF",
      subscriptionTrafficBackgroundColor: "#4E1220FF",
      subscriptionInfoTextColor: "#FFF0F3FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#ECA3B0FF",
      serverRowChevronColor: "#E63956FF",
      additionalOptionsButtonColor: "#E63956FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#E63956FF", "#B01E37FF", "#FF758FFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "bio-mint",
    name: "Bio Mint",
    swatches: ["#071B16", "#38EF7D"],
    config: {
      backgroundGradientRotationAngle: 50,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#04100DFF", "#071B16FF", "#0E3027FF"],
      serverRowBackgroundColor: "#0E2922FF",
      selectedServerRowColor: "#17453AFF",
      subsHeaderColor: "#12362EFF",
      buttonColor: "#38EF7DFF",
      buttonTextColor: "#03140CFF",
      powerIconColor: "#11523EFF",
      serverRowTitleTextColor: "#EFFFF6FF",
      serverRowSubTitleTextColor: "#98E6BFFF",
      topBarButtonsColor: "#38EF7DFF",
      supportIconColor: "#38EF7DFF",
      profileWebPageIconColor: "#38EF7DFF",
      subHeaderButtonColor: "#38EF7DFF",
      settingsControlsTintColor: "#38EF7DFF",
      subscriptionInfoBackgroundColor: "#0B221CFF",
      subscriptionTrafficBackgroundColor: "#164B3FFF",
      subscriptionInfoTextColor: "#EFFFF6FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#98E6BFFF",
      serverRowChevronColor: "#38EF7DFF",
      additionalOptionsButtonColor: "#38EF7DFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#38EF7DFF", "#11998EFF", "#76F5A7FF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "ultraviolet",
    name: "Ultraviolet",
    swatches: ["#080C1A", "#7E57C2"],
    config: {
      backgroundGradientRotationAngle: 55,
      backgroundGradientColorIntensity: 1,
      backgroundColors: ["#040710FF", "#080C1AFF", "#121933FF"],
      serverRowBackgroundColor: "#11172EFF",
      selectedServerRowColor: "#1E274EFF",
      subsHeaderColor: "#17203FFF",
      buttonColor: "#7E57C2FF",
      buttonTextColor: "#090412FF",
      powerIconColor: "#332252FF",
      serverRowTitleTextColor: "#F4F0FCFF",
      serverRowSubTitleTextColor: "#B5A7D8FF",
      topBarButtonsColor: "#7E57C2FF",
      supportIconColor: "#7E57C2FF",
      profileWebPageIconColor: "#7E57C2FF",
      subHeaderButtonColor: "#7E57C2FF",
      settingsControlsTintColor: "#7E57C2FF",
      subscriptionInfoBackgroundColor: "#10162BFF",
      subscriptionTrafficBackgroundColor: "#283463FF",
      subscriptionInfoTextColor: "#F4F0FCFF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#B5A7D8FF",
      serverRowChevronColor: "#7E57C2FF",
      additionalOptionsButtonColor: "#7E57C2FF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#7E57C2FF", "#512DA8FF", "#B39DDBFF"],
      backgroundImageType: "light",
      buttonImageType: "light"
    }
  },
  {
    id: "monolith",
    name: "Monolith",
    swatches: ["#111111", "#9CA3AF"],
    config: {
      backgroundGradientRotationAngle: 0,
      backgroundGradientColorIntensity: 0.9,
      backgroundColors: ["#0A0A0AFF", "#111111FF", "#1B1B1BFF"],
      serverRowBackgroundColor: "#181818FF",
      selectedServerRowColor: "#2B2B2BFF",
      subsHeaderColor: "#202020FF",
      buttonColor: "#9CA3AFFF",
      buttonTextColor: "#0A0A0AFF",
      powerIconColor: "#3A3A3AFF",
      serverRowTitleTextColor: "#F3F4F6FF",
      serverRowSubTitleTextColor: "#9CA3AFFF",
      topBarButtonsColor: "#9CA3AFFF",
      supportIconColor: "#9CA3AFFF",
      profileWebPageIconColor: "#9CA3AFFF",
      subHeaderButtonColor: "#9CA3AFFF",
      settingsControlsTintColor: "#9CA3AFFF",
      subscriptionInfoBackgroundColor: "#161616FF",
      subscriptionTrafficBackgroundColor: "#2E2E2EFF",
      subscriptionInfoTextColor: "#F3F4F6FF",
      disclosureHeaderTextColor: "#FFFFFF",
      disclosureSubHeaderTextColor: "#9CA3AFFF",
      serverRowChevronColor: "#9CA3AFFF",
      additionalOptionsButtonColor: "#9CA3AFFF",
      buttonTimerColor: "#FFFFFF",
      elipseColors: ["#4B5563FF", "#374151FF", "#6B7280FF"],
      backgroundImageType: "dark",
      buttonImageType: "dark"
    }
  }
];

export const EMPTY_THEME: HappThemeConfig = {
  backgroundGradientRotationAngle: 0,
  backgroundGradientColorIntensity: 1,
  backgroundColors: ["#121212FF", "#1A1A1AFF", "#242424FF"],
  serverRowBackgroundColor: "#1E1E1EFF",
  selectedServerRowColor: "#2E2E2EFF",
  subsHeaderColor: "#262626FF",
  buttonColor: "#FFFFFF",
  buttonTextColor: "#000000FF",
  powerIconColor: "#555555FF",
  serverRowTitleTextColor: "#FFFFFFFF",
  serverRowSubTitleTextColor: "#A0A0A0FF",
  topBarButtonsColor: "#FFFFFF",
  supportIconColor: "#FFFFFF",
  profileWebPageIconColor: "#FFFFFF",
  subHeaderButtonColor: "#FFFFFF",
  settingsControlsTintColor: "#FFFFFF",
  subscriptionInfoBackgroundColor: "#1C1C1CFF",
  subscriptionTrafficBackgroundColor: "#333333FF",
  subscriptionInfoTextColor: "#FFFFFFFF",
  disclosureHeaderTextColor: "#FFFFFFFF",
  disclosureSubHeaderTextColor: "#A0A0A0FF",
  serverRowChevronColor: "#A0A0A0FF",
  additionalOptionsButtonColor: "#FFFFFFFF",
  buttonTimerColor: "#FFFFFFFF",
  elipseColors: ["#333333FF", "#222222FF", "#444444FF"],
  backgroundImageType: "dark",
  buttonImageType: "dark"
};
